<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Source generators must target netstandard 2.0 -->
		<TargetFramework>netstandard2.0</TargetFramework>
		<!-- Do not include the generator as a lib dependency -->
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<!--Mark the nuget as a dev dependency, so any projects using this nuget don't auto pull in this project-->
		<DevelopmentDependency>true</DevelopmentDependency>
		<IsPackable>true</IsPackable>
		<!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
		<!--Skip Package Analysis because it'll complain we don't have any files at the "lib/netstandard2.0" path, which is okay because this is a source generator-->
		<NoPackageAnalysis>true</NoPackageAnalysis>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ProgrammerAl.SourceGenerators.PublicInterfaceGenerator</RootNamespace>
		<AssemblyName>ProgrammerAl.SourceGenerators.PublicInterfaceGenerator</AssemblyName>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup>
		<Version>0.1.0</Version>
		<Title>Public Interface Generator</Title>
		<Authors>ProgrammerAL</Authors>
		<Description>A source generator to create C# interfaces based off the public methods/properties/events of a class.</Description>
		<PackageProjectUrl>https://github.com/ProgrammerAL/public-interface-generator</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ProgrammerAL/public-interface-generator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>source generator</PackageTags>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" PrivateAssets="all" />
	</ItemGroup>

	<!--<ItemGroup>
		<PackageReference Include="ProgrammerAl.SourceGenerators.PublicInterfaceGenerator.Attributes" Version="*" GeneratePathProperty="true" PrivateAssets="all" />
	</ItemGroup>-->
	<!-- Reference the attributes from the generator to compile against them -->
	<!-- Ensure we specify PrivateAssets so the NuGet doesn't have any dependencies -->
	<!--<ItemGroup>
		<ProjectReference Include="..\PublicInterfaceGenerator.Attributes\PublicInterfaceGenerator.Attributes.csproj" PrivateAssets="All" />
	</ItemGroup>-->

	<ItemGroup>
		<!-- Anyone using the generator needs to use the attributes NuGet so any reflection doesn't throw when it sees the attributes in code -->
		<PackageReference Include="ProgrammerAl.SourceGenerators.PublicInterfaceGenerator.Attributes" Version="1.*" />

		<!-- Package the generator in the analyzer directory of the nuget package -->
		<None Include="$(OutputPath)/$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

		<!--Pack the attributes dll in the lib\netstandard2.0 path so the library consuming this nuget can use it-->
		<None Include="$(OutputPath)/ProgrammerAl.SourceGenerators.PublicInterfaceGenerator.Attributes.dll" Pack="true" PackagePath="lib/netstandard2.0" Visible="false" />

		<None Include="../../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<!--<PropertyGroup>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
	</PropertyGroup>

	<Target Name="GetDependencyTargetPaths">
		<ItemGroup>
			<TargetPathWithTargetPlatformMoniker Include="$(PKGProgrammerAl_SourceGenerators_PublicInterfaceGenerator_Attributes)\lib\netstandard2.0\ProgrammerAl.SourceGenerators.PublicInterfaceGenerator.Attributes.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
	</Target>-->

	<PropertyGroup>
		<NuGetAudit>true</NuGetAudit>
		<NuGetAuditMode>all</NuGetAuditMode>
		<NuGetAuditLevel>low</NuGetAuditLevel>
	</PropertyGroup>
</Project>